import { getDatabase } from '@config/database';
import type { User, CreateUserData } from '@typings/auth.types';

// Map snake_case DB row to camelCase User interface
function rowToUser(row: Record<string, unknown>): User {
  return {
    id: row['id'] as string,
    emailEncrypted: row['email_encrypted'] as string,
    emailHash: row['email_hash'] as string,
    passwordHash: row['password_hash'] as string,
    isActive: Boolean(row['is_active']),
    emailVerified: Boolean(row['email_verified']),
    totpEnabled: Boolean(row['totp_enabled']),
    totpSecretEncrypted: (row['totp_secret_encrypted'] as string | null) ?? null,
    webauthnEnabled: Boolean(row['webauthn_enabled']),
    failedLoginAttempts: Number(row['failed_login_attempts']),
    lockedUntil: row['locked_until'] ? new Date(row['locked_until'] as string) : null,
    lastLoginAt: row['last_login_at'] ? new Date(row['last_login_at'] as string) : null,
    createdAt: new Date(row['created_at'] as string),
    updatedAt: new Date(row['updated_at'] as string),
  };
}

class UserRepository {
  private get db() {
    return getDatabase();
  }

  async findById(id: string): Promise<User | null> {
    const row = await this.db('users').where({ id }).first();
    return row ? rowToUser(row as Record<string, unknown>) : null;
  }

  async findByEmailHash(emailHash: string): Promise<User | null> {
    const row = await this.db('users').where({ email_hash: emailHash }).first();
    return row ? rowToUser(row as Record<string, unknown>) : null;
  }

  async existsByEmailHash(emailHash: string): Promise<boolean> {
    const result = await this.db('users')
      .where({ email_hash: emailHash })
      .count('id as count')
      .first();
    return Number(result?.['count'] ?? 0) > 0;
  }

  async create(data: CreateUserData): Promise<User> {
    const db = this.db;
    await db('users').insert({
      email_encrypted: data.emailEncrypted,
      email_hash: data.emailHash,
      password_hash: data.passwordHash,
    });
    // MySQL insert returns the auto-increment ID, but we use UUIDs generated by DB
    // Fetch the created row by email_hash (guaranteed unique)
    const row = await db('users').where({ email_hash: data.emailHash }).first();
    return rowToUser(row as Record<string, unknown>);
  }

  async updateFailedAttempts(
    userId: string,
    attempts: number,
    lockedUntil: Date | null
  ): Promise<void> {
    await this.db('users').where({ id: userId }).update({
      failed_login_attempts: attempts,
      locked_until: lockedUntil,
    });
  }

  async resetFailedAttempts(userId: string): Promise<void> {
    await this.db('users').where({ id: userId }).update({
      failed_login_attempts: 0,
      locked_until: null,
    });
  }

  async updateLastLogin(userId: string): Promise<void> {
    await this.db('users').where({ id: userId }).update({
      last_login_at: new Date(),
    });
  }

  async updateTotpSecret(userId: string, encryptedSecret: string): Promise<void> {
    await this.db('users').where({ id: userId }).update({
      totp_secret_encrypted: encryptedSecret,
    });
  }

  async enableTotp(userId: string): Promise<void> {
    await this.db('users').where({ id: userId }).update({
      totp_enabled: true,
    });
  }

  async disableTotp(userId: string): Promise<void> {
    await this.db('users').where({ id: userId }).update({
      totp_enabled: false,
      totp_secret_encrypted: null,
    });
  }

  async enableWebAuthn(userId: string): Promise<void> {
    await this.db('users').where({ id: userId }).update({
      webauthn_enabled: true,
    });
  }
}

export const userRepository = new UserRepository();
